- name: deb-utils
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - git
      - emacs
      - python3
      - python3-pip
      - exa
      - bat
      - jq
  tasks:
    - name: install deb-utils packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
  tags:
    - deb-utils

- name: Rust
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - rm-improved
      - just
  tasks:
    - name: Download Installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
    - name: Install rust/cargo
      shell: /tmp/sh.rustup.rs -y
#    - name: Install rust packages
#      community.general.cargo:
#        name: "{{ item }}"
#        state: latest
#      loop: "{{ packages }}"
  tags:
    - rust

- name: Kitty
  hosts: localhost
  connection: local
  become: true
  vars:
    user: galep
  tasks:
    - name: Download Installer
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: /tmp/kitty-installer.sh
        mode: '0755'
        force: 'yes'
    - name: Install kitty
      shell: /tmp/kitty-installer.sh
    - name: Create a symbolic link to add kitty to PATH
      file:
        src: /home/{{ user }}/.local/kitty.app/bin/kitty
        dest: /home/{{ user }}/.local/bin/kitty
        state: link
        force: yes
    - name: Place the kitty.desktop file somewhere it can be found by the OS
      copy:
        src: ~/.local/kitty.app/share/applications/kitty.desktop
        dest: ~/.local/share/applications/
    - name: Update the paths to the kitty and its icon in the kitty.desktop file(s)
      shell: |
        sed -i "s|Icon=kitty|Icon=/home/{{ user }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
        sed -i "s|Exec=kitty|Exec=/home/{{ user }}/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
  tags:
    - kitty

- name: Lazygit
  hosts: localhost
  connection: local
  become: true
  gather_facts: no
  tasks:
    - name: Get lazygit version
      shell: curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/'
      register: lazygit_version
    - debug: var=lazygit_version.stdout_lines
    - name: Download archive
      get_url:
        url: https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout_lines[0] }}_Linux_x86_64.tar.gz
        dest: /tmp/lazygit.tar.gz
    - name: Install lazygit
      unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /usr/local/bin
  tags:
    - lazygit