
- name: Setup
  hosts: localhost
  connection: local
  vars:
    user: galep
    directories:
      - perso
      - projects
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: /home/{{ user }}/{{ item }}
        state: directory
      loop: "{{ directories }}"

- name: Apt packages
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - git
      - emacs
      - python3
      - python3-pip
      - exa
      - bat
      - jq
      - gdb
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
  tags:
    - deb-utils

- name: Rust
  hosts: localhost
  connection: local
  vars:
    packages:
      - rm-improved
      - just
  tasks:
    - name: Check if cargo is installed
      ansible.builtin.shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
    - name: Download Installer
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
    - name: Install rust/cargo
      when: cargo_exists is failed
      ansible.builtin.script:
        cmd: /tmp/sh.rustup.rs -y
    - name: Install rust packages
      community.general.cargo:
        name: "{{ item }}"
      loop: "{{ packages }}"
  tags:
    - rust

- name: Kitty
  hosts: localhost
  connection: local
  vars:
    user: galep
  tasks:
    - name: Check if kitty is installed
      ansible.builtin.shell: command -v kitty
      register: kitty_exists
      ignore_errors: yes
    - name: Download Installer
      when: kitty_exists is failed
      ansible.builtin.get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: /tmp/kitty-installer.sh
        mode: '0544'
        force: 'yes'
    - name: Install kitty
      when: kitty_exists is failed
      ansible.builtin.script:
        cmd: /tmp/kitty-installer.sh
    - name: Create a symbolic link to add kitty to PATH
      when: kitty_exists is failed
      ansible.builtin.file:
        src: /home/{{ user }}/.local/kitty.app/bin/kitty
        dest: /home/{{ user }}/.local/bin/kitty
        state: link
        mode: '0744'
        force: true
    - name: Place the kitty.desktop file somewhere it can be found by the OS
      when: kitty_exists is failed
      ansible.builtin.copy:
        src: ~/.local/kitty.app/share/applications/kitty.desktop
        dest: ~/.local/share/applications/
        mode: '0755'
    - name: Update the paths to the icon in the kitty.desktop file(s)
      when: kitty_exists is failed
      ansible.builtin.lineinfile:
        path: /home/{{ user }}/.local/share/applications/kitty*.desktop
        search_string: 'Icon=kitty'
        line: 'Icon=/home/{{ user }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png'
    - name: Update the paths to the binary in the kitty.desktop file(s)
      when: kitty_exists is failed
      ansible.builtin.lineinfile:
        path: /home/{{ user }}/.local/share/applications/kitty*.desktop
        search_string: 'Exec=kitty'
        line: 'Exec=/home/{{ user }}/.local/kitty.app/bin/kitty'
  tags:
    - kitty

- name: Glow
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check if glow is installed
      ansible.builtin.shell: command -v glow
      register: glow_exists
      ignore_errors: yes
    - name: Get glow version
      when: glow_exists is failed
      ansible.builtin.script:
        cmd: curl -s "https://api.github.com/repos/charmbracelet/glow/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/'
      register: latest_version
    - name: Download archive
      when: glow_exists is failed
      ansible.builtin.get_url:
        url: https://github.com/charmbracelet/glow/releases/latest/download/glow_{{ latest_version.stdout_lines[0] }}_Darwin_x86_64.tar.gz
        dest: /tmp/glow.tar.gz
        mode: '0544'
    - name: Install lazygit
      when: glow_exists is failed
      ansible.builtin.unarchive:
        src: /tmp/glow.tar.gz
        dest: /usr/local/bin
  tags:
    - glow

- name: Lazygit
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get lazygit version
      ansible.builtin.script:
        cmd: curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/'
      register: lazygit_version
    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout_lines[0] }}_Linux_x86_64.tar.gz
        dest: /tmp/lazygit.tar.gz
        mode: '0544'
    - name: Install lazygit
      ansible.builtin.unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /usr/local/bin
  tags:
    - lazygit

# https://github.com/pwndbg/pwndbg
- name: pwndbg
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Clone pwndbg repository
      ansible.builtin.git:
        repo: https://github.com/pwndbg/pwndbg
        dest: /home/{{ user }}/projects
