- name: Apt packages
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - git
      - emacs
      - python3
      - python3-pip
      - exa
      - bat
      - jq
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
  tags:
    - deb-utils

- name: Rust
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - rm-improved
      - just
  tasks:
    - name: Download Installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
    - name: Install rust/cargo
      ansible.builtin.script: /tmp/sh.rustup.rs -y
#    - name: Install rust packages
#      community.general.cargomode: '0755':
#        name: "{{ item }}"
#        state: latest
#      loop: "{{ packages }}"
  tags:
    - rust

- name: Kitty
  hosts: localhost
  connection: local
  become: true
  vars:
    user: galep
  tasks:
    - name: Download Installer
      ansible.builtin.get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: /tmp/kitty-installer.sh
        mode: '0544'
        force: 'yes'
    - name: Install kitty
      ansible.builtin.script: /tmp/kitty-installer.sh
    - name: Create a symbolic link to add kitty to PATH
      ansible.builtin.file:
        src: /home/{{ user }}/.local/kitty.app/bin/kitty
        dest: /home/{{ user }}/.local/bin/kitty
        state: link
        mode: '0744'
        force: true
    - name: Place the kitty.desktop file somewhere it can be found by the OS
      ansible.builtin.copy:
        src: ~/.local/kitty.app/share/applications/kitty.desktop
        dest: ~/.local/share/applications/
        mode: '0755'
    - name: Update the paths to the icon in the kitty.desktop file(s)
      ansible.builtin.lineinfile:
        path: /home/{{ user }}/.local/share/applications/kitty*.desktop
        search_string: 'Icon=kitty'
        line: 'Icon=/home/{{ user }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png'
    - name: Update the paths to the binary in the kitty.desktop file(s)
      ansible.builtin.lineinfile:
        path: /home/{{ user }}/.local/share/applications/kitty*.desktop
        search_string: 'Exec=kitty'
        line: 'Exec=/home/{{ user }}/.local/kitty.app/bin/kitty'
  tags:
    - kitty

- name: Lazygit
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Get lazygit version
      ansible.builtin.shell: |
        set -o pipefail && \
        curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/'
      register: lazygit_version
      changed_when: false
    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout_lines[0] }}_Linux_x86_64.tar.gz
        dest: /tmp/lazygit.tar.gz
        mode: '0544'
    - name: Install lazygit
      ansible.builtin.unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /usr/local/bin
  tags:
    - lazygit
